engTrans =
{
	"tutorial_1_desc": "This is a short instruction before the challenge starts.\nClicking on the board using the mouse can fill in or remove blocks.\nUse the mouse to fill a sequence of blocks on the board.",
	"tutorial_next_button": "Next >",
	"tutorial_back_button": "< Back",
	"tutorial_2_desc": "tutorial_2_text",
	"game_design_title": "Design",
	"design_button_submit": "Test",
	"design_button_clearall": "Clear",
	"game_desc": "Challange - game description",
	"production_title": "Production",
	"score_title": "Results",
	"scoreboard_grey_cells": "Blocks",
	"scoreboard_penalty_cells": "Mismatched",
	"scoreboard_effiency": "Structure's cost",
	"scoreboard_high_score": "Your lowest Structure's cost",
	"press_submit": "Press Test before pressing Next",
	"tutorial_3_desc": "tutorial_3_text",
	"tutorial_4_desc": "tutorial_4_text",
	"tutorial_5_desc": "Imagine wrapping a string around a Structure- This will create a shape on the Production board.\nPress Test to create a shape.",
	"tutorial_6_desc": "Blocks are used to construct structures. A structure is a set of interconnected blocks.\nAdd one block to construct a structure.",
	"tutorial_7_desc": "Notice that corners of blocks do not establish connections.\nAdd one block to achieve a valid Structure.",
	"tutorial_8_desc": "tutorial_8_text not adjacent",
	"tutorial_9_desc": "Add some blocks to achieve a valid Structure.",
	"tutorial_10_desc": "Every shape you create will be compared to a circle.\nPress Test to create a shape and observe its overlapping with the circle",
	"tutorial_10_2_desc": "Cells assigned to the shape but not to the circle and vice versa are marked by red X’s.\nThese cells do not match the shape created and the circle.",
	"tutorial_11_desc": "Every block costs 1 point.\nEvery mismatched cell costs 1 point.\nThe cost of the tested Structure is displayed.",
	"tutorial_11_2_desc": "The challenge -\nDesign a Structure that reduces costs to the minimum!",
	"tutorial_12_1_desc": "You will have {0} minutes for the task.",
	"tutorial_2_check_fail": "Please fill in at least 5-10 blocks",
	"tutorial_12_desc": "Design a Structure with the lowest cost.",
	"no_connectivity": "This is not a valid Structure.\nCorrect the design - all blocks must be interconnected.",
	"test_end": "End of game",
	"intro_large_header": "Welcome to the Game of -",
	"intro_large_header_2": "Structures",
	"start_button": "Start",
	"intro_small_header": "Please enter the unique id given to you",
	"minimize_grey_cells": "Well done. Minimize further the number of blocks",
	"game_desc": "Design and test structures on the Design Board to maximize overlaps with the circle on the Production Board.\nAim for cost-efficiency by minimizing block usage and reducing mismatched cells.\nKeep refining your structures until the time is up",
	"timer_desc": "Time left"
};